# Generated by Django 2.0 on 2021-08-30 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Total', models.FloatField(default=250.0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory', models.CharField(default='Product Category', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(default='Product Name', max_length=255)),
                ('Product_Title', models.CharField(default='Product Name', max_length=255)),
                ('Product_Image', models.ImageField(default='abc.jpg', upload_to='productimages/')),
                ('Product_Price', models.FloatField(default=0.0)),
                ('Product_MRP', models.FloatField(default=0.0)),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('Review', models.CharField(default='Very Nice', max_length=255)),
                ('Review_Date', models.DateField(auto_now_add=True)),
                ('getprod', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='xyz@12', max_length=100)),
                ('Sname', models.CharField(default='Seller Name', max_length=255)),
                ('shop_name', models.CharField(default='Shop Name', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(default='123')),
                ('address1', models.CharField(default='Address 1', max_length=255)),
                ('address2', models.CharField(default='Address 2', max_length=255)),
                ('City', models.CharField(default='City', max_length=200)),
                ('state', models.CharField(default='state', max_length=200)),
                ('Pincode', models.IntegerField(default='000000')),
                ('password', models.CharField(default='password', max_length=255)),
                ('OTP', models.IntegerField(default='123456')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='xyz@12', max_length=100)),
                ('Ufname', models.CharField(default='Seller Name', max_length=255)),
                ('Ulname', models.CharField(default='Shop Name', max_length=255)),
                ('Uemail', models.EmailField(max_length=254, unique=True)),
                ('Umobile', models.BigIntegerField(default='123')),
                ('Uaddress1', models.CharField(default='Address1', max_length=255, null=True)),
                ('Uaddress2', models.CharField(default='Address2', max_length=255, null=True)),
                ('UCity', models.CharField(default='City', max_length=255, null=True)),
                ('UState', models.CharField(default='State', max_length=255, null=True)),
                ('UPincode', models.IntegerField(default='000000')),
                ('Upassword', models.CharField(default='password', max_length=255)),
                ('UOTP', models.IntegerField(default='123456')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='getuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='Seller_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seller'),
        ),
        migrations.AddField(
            model_name='cart',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='getprod',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
