# Generated by Django 2.0 on 2021-08-30 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(default=100000, primary_key=True, serialize=False)),
                ('Order_Date', models.DateField(auto_now_add=True)),
                ('Seller_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seller')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
