# Generated by Django 2.0 on 2021-08-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210811_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Total', models.IntegerField(default=250)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('getprod', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
