# Generated by Django 2.0 on 2021-08-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
